### ISSUE TITLE
LCD.NUT error in code

### ISSUE THREAD

**Issue by jaseiffert** [esquiloio/lib#1]
In the setContrast() function there is this line.
_lcd.setContrast(level);

I believe it should be:
_nhd.setContrast(level);

Received an error and that is what I changed to make it work.

Thanks,

Jeffery

**Comment by esquiloio** [comment]
Fixed in https://github.com/esquiloio/lib/commit/6ce8987a9c97ee097ec3295d8703ae87c4431848
